# Generated by Django 6.0.5 on 2026-05-14 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LiveSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classroom', models.CharField(default='default', max_length=50)),
                ('subject', models.CharField(blank=True, max_length=100)),
                ('date', models.DateField(auto_now_add=True)),
                ('source_type', models.CharField(choices=[('webcam', 'Local Webcam'), ('rtsp', 'RTSP CCTV Camera')], default='webcam', max_length=10)),
                ('rtsp_url', models.CharField(blank=True, max_length=500)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('stopped', 'Stopped')], default='pending', max_length=20)),
                ('log_output', models.TextField(blank=True)),
                ('total_frames_processed', models.IntegerField(default=0)),
                ('total_detections', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('roll_number', models.CharField(max_length=50, unique=True)),
                ('student_id', models.CharField(blank=True, max_length=50)),
                ('classroom', models.CharField(blank=True, default='default', max_length=50)),
                ('section', models.CharField(blank=True, max_length=10)),
                ('parent_contact', models.CharField(blank=True, max_length=20)),
                ('face_encoding', models.BinaryField(blank=True, null=True)),
                ('n_embeddings', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['roll_number'],
            },
        ),
        migrations.CreateModel(
            name='HourlyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_number', models.IntegerField()),
                ('period_start', models.DateTimeField()),
                ('period_end', models.DateTimeField()),
                ('frames_processed', models.IntegerField(default=0)),
                ('total_face_detections', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='facerecognition.livesession')),
            ],
            options={
                'ordering': ['session', 'report_number'],
                'unique_together': {('session', 'report_number')},
            },
        ),
        migrations.CreateModel(
            name='StudentPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='student_photos/')),
                ('embedding_extracted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='facerecognition.student')),
            ],
        ),
        migrations.CreateModel(
            name='DailyAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reports_present_in', models.IntegerField(default=0)),
                ('total_reports', models.IntegerField(default=0)),
                ('presence_percentage', models.FloatField(default=0.0)),
                ('final_status', models.CharField(default='Absent', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_attendance', to='facerecognition.livesession')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facerecognition.student')),
            ],
            options={
                'ordering': ['student__roll_number'],
                'unique_together': {('session', 'student')},
            },
        ),
        migrations.CreateModel(
            name='StudentDetection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detection_count', models.IntegerField(default=0)),
                ('best_confidence', models.FloatField(default=0.0)),
                ('was_present', models.BooleanField(default=False)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detections', to='facerecognition.hourlyreport')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facerecognition.student')),
            ],
            options={
                'unique_together': {('report', 'student')},
            },
        ),
    ]
